version: "3.8"

services:
  app:
    build: .
    container_name: online_courses_management
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy
      mysql:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongodb:27018/online_courses_management
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=nestcourse
      - MYSQL_PASSWORD=nestpassword
      - MYSQL_DATABASE=online_courses_management
      - USER_SECRET_KEY=aaaaaaaaaaaaaaaa
    networks:
      - online_courses_management

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27018:27018"
    volumes:
      - mongodb_data:/data/db
    networks:
      - online_courses_management
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: online_courses_management
      MYSQL_USER: nestcourse
      MYSQL_PASSWORD: nestpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - online_courses_management
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "nestcourse", "-pnestpassword"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  online_courses_management:
    driver: bridge

volumes:
  mongodb_data:
  mysql_data:
